version: "3.6"

services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    env_file:
      - .env
    image: python:3.9.5
    ports:
      - "80:80"
      - "5000:5000"
    restart: unless-stopped
