version: "3.6"

services:
  api_server:
    container_name: api-server
    image: jazzdd/alpine-flask:python3
    ports:
      - "80:80"
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./create_endpoints/serializing:/app
